<footer>
        <div class="footer-top">
            <img class="headericon" src="images/logo.png" alt="logo">
        </div>

        <div class="footerinfo">
            <p id="mail"> <strong class="fas fa-map-marker-alt" style= "color: black;"><a href="https://www.google.com/maps/place/Swinburne+University+of+Technology/@-37.8221504,145.0367659,17z/data=!3m1!4b1!4m5!3m4!1s0x6ad642326bae5aaf:0x75e96bbd4988f769!8m2!3d-37.8221504!4d145.0389546"></strong>27 John Street, Hawthorn VIC 3122</a> <strong class="fa fa-envelope"></strong> </p>
			<a href="mailto:104141893@student.swin.edu.au;103605848@student.swin.edu.au;104249085@student.swin.edu.au;103992100@student.swin.edu.au;103885695@student.swin.edu.au">Contact Us ✉</a>
		</div>
        <p id="company-name"> © 2022 Swinburne University of Technology COS10026 Computing Inquiry Project </p>
</footer>